# -*- coding: utf-8 -*-
"""Aditi_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbAEIZf8qKkpskBuclNPFoMWFPoflq5M
"""

!pip install -U langchain langchain-community langchain-text-splitters faiss-cpu sentence-transformers transformers

import os

# =============================
# 📦 IMPORTS
# =============================
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.documents import Document
from langchain_community.llms import HuggingFacePipeline

from langgraph.graph import StateGraph

from transformers import pipeline

# =============================
# 📂 FAKE SUPPORT DATA
# =============================
data = [
    "Q: How to reset the device? A: Hold the power button for 10 seconds.",
    "Q: Battery not charging A: Check cable and adapter.",
    "Q: App not syncing A: Restart Bluetooth and reopen app.",
    "Q: Warranty policy A: 1-year replacement warranty.",
    "Q: Device overheating A: Turn off device and let it cool.",
    "Q: Screen not working A: Restart device or update firmware.",
    "Q: Cannot login A: Reset password using email.",
    "Q: Data not updating A: Check internet connection.",
    "Q: Device not turning on A: Charge for 30 minutes.",
    "Q: Strap broken A: Contact support for replacement."
]

docs = [Document(page_content=d) for d in data]

# =============================
# ✂️ CHUNKING
# =============================
splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=20)
chunks = splitter.split_documents(docs)

# =============================
# 🧠 LOCAL EMBEDDINGS
# =============================
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
db = FAISS.from_documents(chunks, embeddings)
retriever = db.as_retriever()

# =============================
# 🤖 LOCAL LLM
# =============================
pipe = pipeline("text-generation", model="google/flan-t5-base", max_length=200)
llm = HuggingFacePipeline(pipeline=pipe)

# =============================
# ⚙️ GRAPH FUNCTIONS
# =============================
def retrieve(state):
    query = state["query"]
    docs = retriever.invoke(query)
    state["context"] = " ".join([d.page_content for d in docs])
    return state

def generate(state):
    prompt = f"""
Answer the question using the context below.
If unsure, say "I don't know".

Context:
{state['context']}

Question:
{state['query']}
"""
    response = llm.invoke(prompt)
    state["answer"] = response
    return state

def check_confidence(state):
    if "I don't know" in state["answer"]:
        state["confidence"] = "low"
    else:
        state["confidence"] = "high"
    return state

def human_review(state):
    print("\n⚠️ LOW CONFIDENCE ANSWER ⚠️")
    print("AI Answer:", state["answer"])

    choice = input("Approve? (y/n): ")

    if choice == "y":
        return state
    else:
        new_answer = input("Enter corrected answer: ")
        state["answer"] = new_answer
        return state

# =============================
# 🔁 LANGGRAPH WORKFLOW
# =============================
workflow = StateGraph(dict)

workflow.add_node("retrieve", retrieve)
workflow.add_node("generate", generate)
workflow.add_node("check", check_confidence)
workflow.add_node("human", human_review)

workflow.set_entry_point("retrieve")

workflow.add_edge("retrieve", "generate")
workflow.add_edge("generate", "check")

def route(state):
    if state["confidence"] == "low":
        return "human"
    else:
        return "__end__"

workflow.add_conditional_edges("check", route)
workflow.add_edge("human", "__end__")

app = workflow.compile()

# =============================
# ▶️ RUN LOOP
# =============================
while True:
    query = input("\nAsk a question (or type 'exit'): ")

    if query.lower() == "exit":
        break

    result = app.invoke({"query": query})

    print("\n✅ FINAL ANSWER:")
    print(result["answer"])

